### ISSUE TITLE
update docs, metadata, etc.

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-repo-mariadb#8]
### Type of Report

bug

### Actual behaviour

- README.md:
  - no travis header
  - unused modules listed (command)
- community files not included
- LICENSE not shown

### Expected behaviour

docs should be updated
- LICENSE should work
- tests should work
- README.md
  - travis graphic should be added
  - only used modules should be in the modules list

**Comment by daniel-schier** [comment]
The testing is failing, currently.
Maybe you can have alook in the .travis.yml, too.
